name: "spacetraders_dart"
version: "0.1.0"
description: "Dart client for SpaceTraders API"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ">=0.13.0 <0.14.0"
  intl: ^0.18.1
  meta: "^1.1.8"

dev_dependencies:
  test: ^1.24.2
